name = "RvLineList"
uuid = "64580eba-dac5-4344-8efb-4882f76a30da"
authors = ["alexander-wise <esiwrednaxela@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
EchelleCCFs = "5d9f57b1-d7b5-417c-8d79-eedbcaad0187"
EchelleInstruments = "533b6e3a-cbf4-4a92-8a96-bc27ebcb1598"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Pandas = "eadc2687-ae89-51f9-a5d9-86b5a6373a9c"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
RvSpectML = "1f61ac2c-3a1c-440a-925a-2707197041c8"
RvSpectMLBase = "c48404b2-35ea-40e7-ac7f-06a53de703d6"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ArgParse = "1.1.4"
CSV = "0.8.5"
DataFrames = "1.3.4"
EchelleCCFs = "0.2.6"
EchelleInstruments = "0.2.7"
FileIO = "1.15.0"
Interpolations = "0.13.2"
IntervalArithmetic = "0.20.7"
JLD2 = "0.4.22"
Pandas = "1.6.1"
PyCall = "1.93.1"
Query = "1.0.0"
RvSpectML = "0.2.4"
RvSpectMLBase = "0.2.1"
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
